version: '3.8'

services:
  web:
    build: .
    container_name: django_web
    volumes:
      - .:/code
    env_file:
      - .env
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/code/static
    depends_on:
      - web